apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: events-exporter
    app.kubernetes.io/name: kube-events-exporter
    app.kubernetes.io/version: 0.1.0
  name: kube-events-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: events-exporter
      app.kubernetes.io/name: kube-events-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: events-exporter
        app.kubernetes.io/name: kube-events-exporter
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
      - args:
        - --event-types=Warning
        - --involved-object-api-groups=admissionregistration.k8s.io/v1
        - --involved-object-api-groups=apiextensions.k8s.io/v1
        - --involved-object-api-groups=apiregistration.k8s.io/v1
        - --involved-object-api-groups=apps/v1
        - --involved-object-api-groups=authentication.k8s.io/v1
        - --involved-object-api-groups=authorization.k8s.io/v1
        - --involved-object-api-groups=autoscaling/v1
        - --involved-object-api-groups=batch/v1
        - --involved-object-api-groups=batch/v1beta1
        - --involved-object-api-groups=certificates.k8s.io/v1beta1
        - --involved-object-api-groups=coordination.k8s.io/v1
        - --involved-object-api-groups=discovery.k8s.io/v1beta1
        - --involved-object-api-groups=extensions/v1beta1
        - --involved-object-api-groups=monitoring.coreos.com/v1
        - --involved-object-api-groups=networking.k8s.io/v1
        - --involved-object-api-groups=networking.k8s.io/v1beta1
        - --involved-object-api-groups=node.k8s.io/v1beta1
        - --involved-object-api-groups=policy/v1beta1
        - --involved-object-api-groups=rbac.authorization.k8s.io/v1
        - --involved-object-api-groups=scheduling.k8s.io/v1
        - --involved-object-api-groups=storage.k8s.io/v1
        - --involved-object-api-groups=v1
        - --involved-object-namespaces=default
        - --involved-object-namespaces=kube-node-lease
        - --involved-object-namespaces=kube-public
        - --involved-object-namespaces=kube-system
        - --reporting-controllers=attachdetach-controller
        - --reporting-controllers=aws-cloud-provider
        - --reporting-controllers=azure-cloud-provider
        - --reporting-controllers=cidrAllocator
        - --reporting-controllers=cloud-controller-manager
        - --reporting-controllers=cloud-node-lifecycle-controller
        - --reporting-controllers=cloudCIDRAllocator
        - --reporting-controllers=controllermanager
        - --reporting-controllers=cronjob-controller
        - --reporting-controllers=daemonset-controller
        - --reporting-controllers=deployment-controller
        - --reporting-controllers=endpoint-controller
        - --reporting-controllers=endpoint-slice-controller
        - --reporting-controllers=g-cloudprovider
        - --reporting-controllers=horizontal-pod-autoscaler
        - --reporting-controllers=ipallocator-repair-controller
        - --reporting-controllers=job-controller
        - --reporting-controllers=kube-controller-manager
        - --reporting-controllers=kube-proxy
        - --reporting-controllers=kubelet
        - --reporting-controllers=node-controller
        - --reporting-controllers=persistentvolume-controller
        - --reporting-controllers=portallocator-repair-controller
        - --reporting-controllers=replicaset-controller
        - --reporting-controllers=replication-controller
        - --reporting-controllers=route_controller
        - --reporting-controllers=scheduler
        - --reporting-controllers=service-controller
        - --reporting-controllers=statefulset-controller
        - --reporting-controllers=taint-controller
        - --reporting-controllers=ttl-after-finished-controller
        - --reporting-controllers=volume_expand
        image: quay.io/dgrisonnet/kube-events-exporter:v0.1.0
        name: kube-events-exporter
        ports:
        - containerPort: 8080
          name: event
        - containerPort: 8081
          name: exporter
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: kube-events-exporter
