run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - goconst
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - varcheck

issues:
  exclude-use-default: false
