os: linux
dist: xenial
language: go

go: "1.14.x"

services:
  - docker

stages:
  - vendor
  - generate
  - lint
  - build
  - test
  - deploy

jobs:
  include:
    - stage: vendor
      name: Vendor
      script: make vendor && git diff --exit-code

    - stage: generate
      name: Generate
      script: make generate && git diff --exit-code

    - stage: lint
      name: Lint
      script: make lint

    - stage: build
      name: Build
      script: make build

    - stage: test
      name: Unit tests
      script: make test-unit
    - name: End to end tests
      script: ./scripts/travis-e2e.sh

    - stage: deploy
      name: Deploy image to quay.io
      script: skip
      before_deploy:
        - docker login -u "$QUAY_USERNAME" --password-stdin quay.io <<< "$QUAY_PASSWORD"
      deploy:
        - provider: script
          script: TAG=latest ./scripts/push-docker-images.sh
          on:
            branch: master
        - provider: script
          script: TAG=$TRAVIS_TAG ./scripts/push-docker-images.sh
          on:
            tags: true
      after_deploy:
        docker logout quay.io
