os: linux
dist: xenial
language: go

go: "1.14.x"

services:
  - docker

branches:
  only:
    - master

stages:
  - vendor
  - lint
  - build
  - test
  - deploy

jobs:
  include:
    - stage: vendor
      name: Vendor
      script: make vendor && git diff --exit-code

    - stage: lint
      name: Lint
      script: make lint

    - stage: build
      name: Build
      script: make build

    - stage: test
      name: Unit tests
      script: make test-unit
    - name: End to end tests
      script: make test-e2e

    - stage: deploy
      name: Deploy image to quay.io
      script: skip
      before_deploy:
        - docker login -u "$QUAY_USERNAME" --password-stdin quay.io <<< "$QUAY_PASSWORD"
      deploy:
        - provider: script
          script: VERSION=latest make container-push
          on:
            branch: master
        - provider: script
          script: VERSION=$TRAVIS_TAG make container-push
          on:
            tags: true
            all_branches: true
      after_deploy:
        docker logout quay.io
