apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-events-exporter
    app.kubernetes.io/version: latest
  name: kube-events-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kube-events-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: kube-events-exporter
        app.kubernetes.io/version: latest
    spec:
      containers:
      - name: kube-events-exporter
        image: quay.io/dgrisonnet/kube-events-exporter:latest
        ports:
        - name: event
          containerPort: 8080
        - name: exporter
          containerPort: 8081
