apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: events-exporter
    app.kubernetes.io/name: kube-events-exporter
    app.kubernetes.io/version: 0.0.0
  name: kube-events-exporter
  namespace: default
