apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: events-exporter
    app.kubernetes.io/name: kube-events-exporter
    app.kubernetes.io/version: 0.1.0
  name: kube-events-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: events-exporter
      app.kubernetes.io/name: kube-events-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: events-exporter
        app.kubernetes.io/name: kube-events-exporter
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
      - args: []
        image: quay.io/dgrisonnet/kube-events-exporter:v0.1.0
        name: kube-events-exporter
        ports:
        - containerPort: 8080
          name: event
        - containerPort: 8081
          name: exporter
      - args:
        - --logtostderr
        - --secure-listen-address=:8443
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - --upstream=http://127.0.0.1:8080/
        image: quay.io/brancz/kube-rbac-proxy:v0.6.0
        name: kube-rbac-proxy-event
        ports:
        - containerPort: 8443
          name: https-event
        securityContext:
          runAsUser: 65534
      - args:
        - --logtostderr
        - --secure-listen-address=:9443
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - --upstream=http://127.0.0.1:8081/
        image: quay.io/brancz/kube-rbac-proxy:v0.6.0
        name: kube-rbac-proxy-exporter
        ports:
        - containerPort: 9443
          name: https-exporter
        securityContext:
          runAsUser: 65534
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: kube-events-exporter
